sudo: required

language: minimal

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_install:
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - cp .env.travis .env

install:
  - docker-compose up -d --build prod

script:
  - curl --silent --fail --show-error http://127.0.0.1:88

after_failure:
  - docker-compose exec prod bash -c "tail /var/log/nginx/access.log"
  - docker-compose exec prod bash -c "tail /var/log/nginx/error.log"

before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
